### ISSUE TITLE
Compiled project missing files. Won't run on 64 bit linux.

### ISSUE THREAD

**Issue by GenTxt** [ReleasedBrainiac/RNN_Text_Gen#1]
Hello:

I'm new to java, maven, and eclipse. I've compiled this project on 64 bit ubuntu linux with jdk 1.8 and jdk 1.7 using maven as recommended but when I try to run the java program from the terminal it throws the following errors:

$ java -jar RNN_Prototype-0.0.1-SNAPSHOT.jar
no main manifest attribute, in RNN_Prototype-0.0.1-SNAPSHOT.jar

$ java -jar RNN_Prototype-0.0.1-SNAPSHOT-bin.jar
no main manifest attribute, in RNN_Prototype-0.0.1-SNAPSHOT-bin.jar

I asked an experienced java programmer to take a look at the code and he couldn't get it to work. What are we missing? Could you explain how to compile so it runs on 64 bit linux?

Thanks

**Comment by ReleasedBrainiac** [comment]
Hello,

i restructure the project at first so maybe this can fix your problem. 

Cheers

**Comment by ReleasedBrainiac** [comment]
I edited the structure and i add a readme for you and all others. Please read it. It contains informations about  where to get the whole example.

More examples you can find there: https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/character/CharacterIterator.java

**Comment by ReleasedBrainiac** [comment]
By the way i need to fix the learning set import because i did it the wrong way

**Comment by ReleasedBrainiac** [comment]
Another thing about eclipse is you can use the maven plugin if you like but if an error occurr just rebuild with desktop maven ;)

**Comment by ReleasedBrainiac** [comment]
The program need some more updates. I think at the end of the week, i can do this. Currently i have a heavy load of work.

**Comment by GenTxt** [comment]
Thanks. Looking forward to the changes. Compiled the current archive and it still generates the same errors.

$ java -jar RNN_Prototype-0.0.1-SNAPSHOT-bin.jar

no main manifest attribute, in RNN_Prototype-0.0.1-SNAPSHOT-bin.jar

$ java -jar RNN_Prototype-0.0.1-SNAPSHOT-bin.jar

no main manifest attribute, in RNN_Prototype-0.0.1-SNAPSHOT-bin.jar

**Comment by ReleasedBrainiac** [comment]
I see a something you need to try.

=> How to get Jar from Maven project => https://www.mkyong.com/maven/how-to-build-project-with-maven/

**Comment by ReleasedBrainiac** [comment]
Maven jars gonna be created on a other way then general java projects. If you face another project configuration than the general Java (for example Maven, Gradle or AspectJ) just look first the way to get the desired type of Data. I faced that problem much times.

**Comment by GenTxt** [comment]
Thanks. I've tried both mvn install and mvn package commands. The results and errors are the same.

**Comment by ReleasedBrainiac** [comment]
I will take a look at the next week iam really in trouble with other work currently
